timeout: 1800s

substitutions:
  _IMAGE_TAG: 'monthly-${SHORT_SHA}'
  _REGION: 'us-central1'
  _AR_REPO: 'us-central1-docker.pkg.dev/${PROJECT_ID}/sp500-dashboard'

steps:
  # Step 1: Run Python analysis (pre-baked image with all deps)
  - id: 'analyze'
    name: '${_AR_REPO}/python-builder:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd /workspace/sp500-portfolio
        python main.py
        LATEST=$$(ls -t data/output/sp500_analysis_*.xlsx | head -1)
        cp "$$LATEST" /workspace/sp500-dashboard/data/sp500_analysis.xlsx
        echo "Copied: $$LATEST"
    timeout: 1200s

  # Step 2: Validate the Excel output
  - id: 'validate'
    name: 'python:3.12-slim'
    entrypoint: 'python'
    args:
      - '-c'
      - |
        import os
        path = '/workspace/sp500-dashboard/data/sp500_analysis.xlsx'
        size = os.path.getsize(path)
        assert size > 102400, f"Excel file too small: {size} bytes (expected >100KB)"
        print(f"Validation passed: {size:,} bytes")
    waitFor: ['analyze']

  # Step 3: Build Next.js Docker image
  - id: 'build'
    name: 'gcr.io/cloud-builders/docker'
    dir: 'sp500-dashboard'
    args:
      - 'build'
      - '-t'
      - '${_AR_REPO}/sp500-dashboard:${_IMAGE_TAG}'
      - '-t'
      - '${_AR_REPO}/sp500-dashboard:latest'
      - '.'
    waitFor: ['validate']

  # Step 4: Push to Artifact Registry
  - id: 'push'
    name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_AR_REPO}/sp500-dashboard'
    waitFor: ['build']

  # Step 5: Deploy to Cloud Run
  - id: 'deploy'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sp500-dashboard'
      - '--image'
      - '${_AR_REPO}/sp500-dashboard:${_IMAGE_TAG}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '3'
    waitFor: ['push']

images:
  - '${_AR_REPO}/sp500-dashboard:${_IMAGE_TAG}'
  - '${_AR_REPO}/sp500-dashboard:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
